In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

In [ ]:
df = pd.read_csv('spam.csv')

In [ ]:
df.head(5)

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
df.Category.value_counts()/len(df)*100

Category
ham     86.593683
spam    13.406317
Name: count, dtype: float64

In [ ]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [ ]:
df.head(5)

  Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [ ]:
df.shape

(5572, 3)

#### **Train Test Split**

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam,test_size=0.2)

In [ ]:
X_train.shape

(4457,)

In [ ]:
X_test.shape

(1115,)

In [ ]:
X_train[:4]

4156    Want a new Video Phone? 750 anytime any networ...
1888    Urgent! Please call 09061743811 from landline....
640     I had askd u a question some hours before. Its...
2311    You have won a Nokia 7250i. This is what you g...
Name: Message, dtype: object

In [ ]:
y_train[:4]

4156    1
1888    1
640     0
2311    1
Name: spam, dtype: int64

#### **Create bag of words representation using CountVectorizer**

In [ ]:
v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_test_cv = v.transform(X_test)

In [ ]:
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59371 stored elements and shape (4457, 7828)>

In [ ]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
X_train_cv.shape

(4457, 7828)

In [ ]:
v.get_feature_names_out()[1750]

'charge'

In [ ]:
v.vocabulary_

{'want': 7455,
 'new': 4818,
 'video': 7361,
 'phone': 5239,
 '750': 631,
 'anytime': 1009,
 'any': 1001,
 'network': 4809,
 'mins': 4554,
 'half': 3344,
 'price': 5462,
 'line': 4188,
 'rental': 5766,
 'free': 3023,
 'text': 6857,
 'for': 2977,
 'months': 4637,
 'reply': 5777,
 'or': 5025,
 'call': 1619,
 '08000930705': 49,
 'delivery': 2259,
 'urgent': 7280,
 'please': 5303,
 '09061743811': 197,
 'from': 3060,
 'landline': 4061,
 'your': 7796,
 'abta': 783,
 'complimentary': 1957,
 'tenerife': 6838,
 'holiday': 3515,
 '5000': 545,
 'cash': 1689,
 'await': 1176,
 'collection': 1913,
 'sae': 5937,
 'cs': 2119,
 'box': 1467,
 '326': 449,
 'cw25wx': 2161,
 '150ppm': 306,
 'had': 3335,
 'askd': 1104,
 'question': 5591,
 'some': 6357,
 'hours': 3560,
 'before': 1300,
 'its': 3820,
 'answer': 992,
 'you': 7790,
 'have': 3398,
 'won': 7658,
 'nokia': 4861,
 '7250i': 626,
 'this': 6921,
 'is': 3800,
 'what': 7554,
 'get': 3159,
 'when': 7560,
 'win': 7603,
 'our': 5060,
 'auction': 1148,
 'to': 7002,
 'take': 6759,
 'part': 5142,
 'send': 6072,
 '86021': 695,
 'now': 4897,
 'hg': 3467,
 'suite342': 6652,
 '2lands': 400,
 'row': 5894,
 'w1jhl': 7414,
 '16': 313,
 'january': 3849,
 'male': 4393,
 'sale': 5949,
 'hot': 3554,
 'gay': 3131,
 'chat': 1762,
 'cheaper': 1768,
 '08709222922': 93,
 'national': 4762,
 'rate': 5638,
 '5p': 573,
 'min': 4541,
 'cheap': 1767,
 '8p': 731,
 'peak': 5185,
 'stop': 6557,
 'texts': 6865,
 '08712460324': 111,
 '10p': 262,
 'customer': 2150,
 'service': 6095,
 'representative': 5782,
 'on': 4986,
 'freephone': 3030,
 '0808': 57,
 '145': 295,
 '4742': 512,
 'between': 1337,
 '9am': 751,
 '11pm': 275,
 'as': 1095,
 'guaranteed': 3306,
 '1000': 252,
 'prize': 5479,
 'also': 935,
 'track': 7077,
 'down': 2452,
 'lighters': 4170,
 'can': 1642,
 'find': 2889,
 'hi': 3469,
 'if': 3644,
 'ur': 7276,
 'lookin': 4257,
 'saucy': 5985,
 'daytime': 2203,
 'fun': 3082,
 'wiv': 7636,
 'busty': 1585,
 'married': 4426,
 'woman': 7655,
 'am': 941,
 'all': 921,
 'next': 4825,
 'week': 7518,
 'sort': 6387,
 'time': 6970,
 '09099726429': 244,
 'janinexx': 3848,
 'calls': 1632,
 'minmobsmorelkpobox177hp51fl': 4550,
 'oh': 4963,
 'must': 4720,
 'taken': 6761,
 'real': 5664,
 'valentine': 7319,
 'out': 5062,
 'shopping': 6174,
 'first': 2907,
 'lol': 4243,
 'no': 4853,
 'babe': 1193,
 'wont': 7665,
 'be': 1272,
 'sliding': 6290,
 'into': 3766,
 'place': 5283,
 'after': 863,
 'midnight': 4530,
 'but': 1587,
 'thanks': 6872,
 'the': 6880,
 'invite': 3775,
 'yeah': 7765,
 'where': 7564,
 'class': 1845,
 'at': 1127,
 'ok': 4968,
 'lor': 4266,
 'yes': 7776,
 'speak': 6418,
 'txt': 7169,
 'hmm': 3499,
 'did': 2321,
 'email': 2599,
 'omg': 4984,
 'joanna': 3886,
 'freaking': 3020,
 'me': 4463,
 'she': 6136,
 'looked': 4256,
 'thru': 6946,
 'my': 4728,
 'friends': 3044,
 'photos': 5246,
 'of': 4942,
 'and': 970,
 'then': 6893,
 'asking': 1107,
 'about': 775,
 'stuff': 6603,
 'myspace': 4731,
 'which': 7570,
 'haven': 3400,
 'even': 2693,
 'logged': 4237,
 'in': 3685,
 'like': 4173,
 'year': 7766,
 'answering': 994,
 'see': 6050,
 'maybe': 4459,
 'better': 1334,
 'reboot': 5682,
 'ym': 7784,
 'got': 3245,
 'photo': 5245,
 'it': 3812,
 'great': 3277,
 '08712402972': 108,
 'immediately': 3670,
 'there': 6897,
 'an': 965,
 'message': 4515,
 'waiting': 7433,
 'dont': 2431,
 'search': 6034,
 'love': 4288,
 'let': 4145,
 'thats': 6879,
 'why': 7584,
 'called': 1625,
 'falling': 2796,
 'bcoz': 1266,
 'force': 2978,
 'yourself': 7800,
 'just': 3931,
 'fall': 2794,
 'know': 4016,
 'smeone': 6311,
 'hold': 3511,
 'bslvyl': 1545,
 'how': 3565,
 'much': 4694,
 'does': 2406,
 'cost': 2044,
 'getting': 3167,
 'tickets': 6958,
 'walsall': 7448,
 'tue': 7143,
 'th': 6867,
 'march': 4414,
 'mate': 4439,
 'them': 6889,
 'sat': 5976,
 'ill': 3656,
 'pay': 5170,
 'treat': 7104,
 'go': 3205,
 'bak': 1212,
 'terry': 6849,
 'reckon': 5699,
 'need': 4785,
 'town': 7074,
 'by': 1603,
 'eightish': 2578,
 'walk': 7438,
 'carpark': 1682,
 'pls': 5311,
 'accept': 792,
 'one': 4990,
 'day': 2201,
 'begging': 1302,
 'change': 1741,
 'number': 4911,
 'jus': 3930,
 'hope': 3534,
 'true': 7123,
 'that': 6877,
 'missin': 4570,
 'cos': 2043,
 'really': 5672,
 'him': 3479,
 'done': 2429,
 'anything': 1008,
 'feel': 2838,
 'guilty': 3320,
 'yet': 7779,
 'we': 7494,
 'finish': 2895,
 'loads': 4225,
 'loans': 4227,
 'are': 1059,
 'babes': 1194,
 'doing': 2420,
 'shit': 6158,
 'nights': 4839,
 'sleep': 6280,
 'fell': 2845,
 'asleep': 1110,
 'knackered': 4009,
 'dreading': 2467,
 'work': 7676,
 'tonight': 7038,
 'thou': 6930,
 'upto': 7275,
 'he': 3409,
 'knows': 4019,
 'lunch': 4320,
 'menu': 4508,
 'only': 4996,
 'da': 2164,
 'account': 803,
 'huh': 3589,
 'so': 6343,
 'early': 2534,
 'having': 3404,
 'dinner': 2351,
 'outside': 5073,
 'izzit': 3831,
 'official': 4955,
 'england': 2627,
 'poly': 5348,
 'ringtone': 5855,
 'colour': 1917,
 'flag': 2920,
 'yer': 7775,
 'mobile': 4602,
 'tonights': 7039,
 'game': 3109,
 'tone': 7032,
 '84199': 688,
 'optout': 5024,
 'eng': 2622,
 'box39822': 1475,
 'w111wx': 7409,
 '50': 543,
 'once': 4988,
 'fishrman': 2910,
 'woke': 7653,
 'mrng': 4673,
 'was': 7469,
 'very': 7350,
 'dark': 2183,
 'waited': 7431,
 'while': 7571,
 'amp': 958,
 'found': 3003,
 'sack': 5933,
 'ful': 3077,
 'stones': 6555,
 'strtd': 6590,
 'throwin': 6943,
 'thm': 6923,
 'in2': 3686,
 'sea': 6033,
 'pass': 5150,
 'atlast': 1132,
 '1stone': 338,
 'sun': 6661,
 'rose': 5887,
 'up': 7259,
 'tht': 6948,
 'those': 6928,
 'nt': 4903,
 'were': 7541,
 'diamonds': 2317,
 'moral': 4640,
 'wake': 7434,
 'good': 3229,
 'night': 4836,
 'bits': 1378,
 'pieces': 5263,
 'sighs': 6214,
 'fine': 2892,
 'll': 4220,
 'sent': 6082,
 'scores': 6013,
 'sophas': 6382,
 'do': 2395,
 'secondary': 6040,
 'application': 1031,
 'few': 2853,
 'schools': 6007,
 'think': 6912,
 'thinking': 6915,
 'applying': 1034,
 'research': 5790,
 'contact': 2002,
 'joke': 3898,
 'ogunrinde': 4962,
 'her': 3454,
 'school': 6006,
 'less': 4141,
 'expensive': 2749,
 'ones': 4991,
 'drinkin': 2475,
 're': 5655,
 'still': 6544,
 'leave': 4118,
 'credit': 2097,
 'card': 1663,
 'gas': 3124,
 'back': 1202,
 'told': 7019,
 'well': 7534,
 'right': 5846,
 'gonna': 3227,
 'check': 1772,
 'today': 7008,
 'steam': 6528,
 'sales': 5950,
 'pee': 5187,
 'come': 1926,
 'bugis': 1562,
 'oso': 5050,
 'near': 4774,
 'wat': 7475,
 'has': 3388,
 'been': 1294,
 'awarded': 1180,
 'with': 7629,
 '2000': 347,
 '09061790121': 200,
 'land': 4059,
 'claim': 1838,
 '3030': 436,
 'valid': 7321,
 '12hrs': 285,
 'tired': 6978,
 'arguing': 1068,
 'same': 5960,
 'sunshine': 6670,
 'quiz': 5600,
 'wkly': 7642,
 'top': 7051,
 'sony': 6375,
 'dvd': 2523,
 'player': 5296,
 'country': 2060,
 'liverpool': 4215,
 'played': 5295,
 'mid': 4528,
 'ansr': 991,
 '82277': 669,
 'sp': 6406,
 'tyrone': 7184,
 'yup': 7813,
 'msg': 4676,
 'tat': 6785,
 'yijue': 7783,
 'tot': 7064,
 'group': 3293,
 'meeting': 4483,
 'mah': 4373,
 'askin': 1106,
 'leaving': 4120,
 'earlier': 2532,
 'mayb': 4458,
 'haf': 3337,
 'far': 2809,
 'hows': 3570,
 'favourite': 2829,
 'person': 5212,
 'workin': 7679,
 'hard': 3378,
 'couldn': 2056,
 'again': 870,
 'last': 4080,
 'nite': 4847,
 'nearly': 4777,
 'rang': 5634,
 '30': 430,
 'whatever': 7555,
 'dear': 2212,
 'morning': 4645,
 'surprised': 6696,
 'guess': 3312,
 'winner': 7613,
 'specially': 6423,
 'selected': 6060,
 'receive': 5688,
 'flights': 2933,
 'inc': 3687,
 'live': 4213,
 'operator': 5012,
 '0871277810910p': 114,
 '18': 318,
 'heard': 3422,
 'not': 4885,
 'guessing': 3316,
 'flaked': 2921,
 'said': 5944,
 'jb': 3860,
 'fantastic': 2807,
 'chance': 1739,
 '150': 300,
 'worth': 7691,
 'discount': 2371,
 'vouchers': 7403,
 'shop': 6172,
 '85023': 692,
 'savamob': 5987,
 'offers': 4952,
 'pobox84': 5331,
 'm263uz': 4341,
 '00': 0,
 'sub': 6614,
 'ela': 2582,
 'kano': 3950,
 'il': 3654,
 'download': 2453,
 'wen': 7536,
 'jade': 3839,
 'paul': 5166,
 'didn': 2323,
 'remember': 5749,
 'barmed': 1231,
 'talk': 6767,
 'amazing': 943,
 'quote': 5603,
 'sometimes': 6365,
 'life': 4161,
 'difficult': 2336,
 'decide': 2221,
 'whats': 7556,
 'wrong': 7712,
 'lie': 4159,
 'brings': 1519,
 'smile': 6313,
 'truth': 7130,
 'tear': 6811,
 'alright': 933,
 'bit': 1373,
 'blankets': 1390,
 'sufficient': 6646,
 'thx': 6954,
 'hey': 3465,
 'sathya': 5979,
 'till': 6968,
 'dint': 2353,
 'meet': 4481,
 'single': 6240,
 'saw': 5991,
 'situation': 6256,
 'latest': 4085,
 'news': 4823,
 'police': 5345,
 'station': 6518,
 'toilet': 7014,
 'stolen': 6550,
 'cops': 2032,
 'nothing': 4888,
 'guessin': 3315,
 'ain': 892,
 'here': 3455,
 'tell': 6826,
 'stupid': 6609,
 'hear': 3421,
 'dad': 2167,
 'brother': 1534,
 'spoken': 6457,
 'knw': 4020,
 'dis': 2362,
 'lt': 4309,
 'gt': 3302,
 'sick': 6210,
 'aight': 891,
 'hello': 3442,
 'st': 6486,
 'andrews': 973,
 'boy': 1481,
 'long': 4250,
 'way': 7489,
 'cold': 1905,
 'will': 7600,
 'keep': 3963,
 'posted': 5388,
 'write': 7704,
 'put': 5573,
 'dictionary': 2320,
 'mode': 4610,
 'cover': 2070,
 'screen': 6026,
 'hand': 3353,
 'press': 5452,
 'gently': 3152,
 'remove': 5759,
 'interesting': 3759,
 'jos': 3909,
 'ask': 1103,
 'wana': 7452,
 've': 7337,
 'lovely': 4291,
 'wisheds': 7622,
 'rock': 5871,
 'nice': 4829,
 'talking': 6771,
 'forget': 2984,
 'pix': 5279,
 'study': 6600,
 'bill': 1355,
 'millers': 4538,
 'performed': 5202,
 'gimme': 3179,
 'lip': 4201,
 'caveboy': 1708,
 'takes': 6762,
 'away': 1181,
 'money': 4627,
 'worries': 7686,
 'care': 1667,
 'financial': 2888,
 'problem': 5486,
 'help': 3445,
 'evening': 2694,
 'try': 7131,
 'something': 6363,
 'read': 5660,
 'exams': 2727,
 'pa': 5097,
 'sitting': 6255,
 'ard': 1058,
 'leh': 4130,
 'busy': 1586,
 'ma': 4348,
 'ashley': 1098,
 'glad': 3191,
 'around': 1081,
 'julianaland': 3924,
 'oblivious': 4933,
 'going': 3217,
 'say': 5992,
 'things': 6911,
 'constantly': 2001,
 'they': 6905,
 'ear': 2531,
 'other': 5052,
 'off': 4944,
 'don': 2427,
 'upset': 7273,
 'listen': 4205,
 'mad': 4360,
 'should': 6186,
 'anthony': 998,
 'bringing': 1518,
 'fees': 2843,
 'rent': 5765,
 'friend': 3043,
 'xam': 7731,
 'hall': 3346,
 'asked': 1105,
 'girl': 3182,
 'starting': 6511,
 'term': 6841,
 'den': 2264,
 'manage': 4396,
 'own': 5091,
 'lot': 4274,
 'hesitation': 3463,
 'silently': 6225,
 'intha': 3765,
 'ponnungale': 5356,
 'ipaditan': 3786,
 'sorry': 6386,
 'sir': 6246,
 'miss': 4567,
 'hr': 3576,
 'trip': 7113,
 'bus': 1580,
 'another': 989,
 'audition': 1150,
 'wednesday': 7515,
 'might': 4532,
 'drive': 2479,
 'eighth': 2577,
 'wondering': 7663,
 'smiling': 6317,
 'coping': 2031,
 'distance': 2380,
 'haha': 3338,
 'legs': 4129,
 'neck': 4782,
 'killing': 3991,
 'amigos': 948,
 'hoping': 3542,
 'end': 2613,
 'burn': 1575,
 'could': 2054,
 'swing': 6727,
 'hour': 3558,
 'anyway': 1010,
 'many': 4408,
 'evenings': 2695,
 'sure': 6689,
 'understand': 7218,
 'wine': 7610,
 'idea': 3635,
 'slurp': 6301,
 'drunkard': 2494,
 'hair': 3342,
 'moment': 4621,
 'wats': 7484,
 'plan': 5287,
 'flowing': 2945,
 'nevering': 4815,
 'bruv': 1544,
 'break': 1499,
 'rewarding': 5836,
 'semester': 6068,
 'offer': 4949,
 'harish': 3384,
 'transfred': 7093,
 'acnt': 812,
 'lei': 4131,
 'fb': 2830,
 'couple': 2063,
 'minutes': 4557,
 'welcome': 7532,
 'age': 872,
 'gender': 3144,
 'begin': 1303,
 '24m': 368,
 'depends': 2275,
 'would': 7696,
 'treated': 7105,
 'freemsg': 3029,
 'records': 5705,
 'indicate': 3711,
 'may': 4457,
 'entitled': 2644,
 '3750': 459,
 'pounds': 5398,
 'accident': 796,
 'opt': 5020,
 'bonus': 1435,
 'caller': 1626,
 '09058095201': 183,
 'conference': 1977,
 'unsubscribed': 7255,
 'services': 6096,
 'tons': 7041,
 'sexy': 6110,
 'hunks': 3600,
 'straight': 6572,
 'http': 3581,
 'gotbabes': 3248,
 'co': 1887,
 'uk': 7195,
 'subscriptions': 6628,
 'whos': 7581,
 'hiya': 3494,
 'comin': 1931,
 'bristol': 1522,
 'april': 1048,
 'les': 4140,
 'rudi': 5911,
 'yrs': 7805,
 'eve': 2692,
 'snoring': 6337,
 'drunk': 2493,
 'college': 1915,
 'sends': 6075,
 'ink': 3728,
 'bath': 1246,
 'todays': 7009,
 'wherre': 7568,
 'boytoy': 1485,
 'booked': 1439,
 'lessons': 4144,
 'liao': 4152,
 'bad': 1204,
 'dat': 2192,
 'gals': 3106,
 'meant': 4470,
 'apology': 1023,
 'texting': 6862,
 'drugs': 2491,
 'girls': 3184,
 'local': 4229,
 'who': 7576,
 'virgins': 7378,
 'ready': 5663,
 '4fil': 524,
 'every': 2700,
 'sexual': 6109,
 'theirs': 6887,
 'cute': 2155,
 '69911': 609,
 '50p': 550,
 'thk': 6922,
 'juz': 3935,
 'accordin': 801,
 'discussed': 2374,
 'yest': 7777,
 'except': 2729,
 'kb': 3960,
 'lesson': 4143,
 'attend': 1140,
 'boys': 1484,
 'xxx': 7742,
 'pics': 5257,
 'direct': 2355,
 'porn': 5367,
 '69855': 605,
 '24hrs': 367,
 'per': 5197,
 'stopbcm': 6559,
 'sf': 6113,
 'wc1n3xx': 7493,
 'opinion': 5013,
 'over': 5078,
 'jada': 3838,
 'kusruthi': 4035,
 'lovable': 4287,
 'silent': 6224,
 'spl': 6447,
 'character': 1748,
 'matured': 4452,
 'stylish': 6612,
 'simple': 6230,
 'phoned': 5242,
 'disconnected': 2370,
 'guy': 3325,
 'browsin': 1541,
 'compulsory': 1959,
 'went': 7538,
 'ganesh': 3113,
 'dress': 2471,
 'somewhere': 6367,
 'angry': 975,
 'happen': 3368,
 'wewa': 7552,
 '130': 288,
 'iriver': 3792,
 '255': 373,
 '128': 283,
 'mb': 4460,
 'home': 3520,
 'cant': 1654,
 'display': 2379,
 'his': 3486,
 'somebody': 6359,
 'secretly': 6044,
 'fancies': 2804,
 'wanna': 7453,
 'give': 3187,
 'us': 7290,
 '09065394514': 212,
 'datebox1282essexcm61xn': 2195,
 '150p': 302,
 'award': 1179,
 '087147123779am': 116,
 '7pm': 644,
 'mr': 4671,
 'sheffield': 6139,
 'play': 5294,
 'okay': 4969,
 'boss': 1455,
 'nanny': 4750,
 'raise': 5618,
 'lay': 4097,
 'man': 4395,
 'missed': 4569,
 'thought': 6932,
 'bimbo': 1362,
 'ugo': 7190,
 'numbers': 4912,
 'appreciate': 1037,
 'safe': 5939,
 'skype': 6274,
 'later': 4084,
 'both': 1457,
 'screwd': 6027,
 'people': 5195,
 'seems': 6056,
 'special': 6420,
 'sight': 6215,
 'remain': 5746,
 'maintain': 4383,
 'ends': 2618,
 'sh': 6115,
 'jas': 3852,
 'moji': 4616,
 'informed': 3722,
 'saved': 5989,
 'lives': 4216,
 'warned': 7464,
 'sprint': 6474,
 'dead': 2207,
 'slow': 6298,
 'prolly': 5508,
 'tomorrow': 7030,
 'oops': 5004,
 'roommate': 5883,
 'transfered': 7090,
 'stock': 6547,
 'reach': 5656,
 'ten': 6836,
 'remind': 5753,
 'shall': 6123,
 'yo': 7786,
 'chad': 1733,
 'gymnastics': 3330,
 'site': 6251,
 'says': 5996,
 'christians': 1827,
 'full': 3079,
 'hellogorgeous': 3443,
 'fone': 2964,
 'charge': 1750,
 'lst': 4308,
 'nitw': 4849,
 'texd': 6856,
 'hopeu': 3541,
 'ad': 826,
 'wkend': 7639,
 'im': 3659,
 '4ward': 539,
 '2mrw': 408,
 'luv': 4324,
 'jaz': 3858,
 'noe': 4856,
 'too': 7043,
 'bored': 1450,
 'dunno': 2515,
 'choose': 1819,
 'late': 4082,
 'fantasy': 2808,
 'football': 2972,
 'tv': 7158,
 'sky': 6272,
 'gamestar': 3111,
 'active': 821,
 '250k': 372,
 'dream': 2468,
 'team': 6809,
 'scoring': 6014,
 'starts': 6512,
 'saturday': 5984,
 'register': 5730,
 '88088': 713,
 '200': 346,
 'cashto': 1692,
 '08000407165': 46,
 'getstop': 3165,
 '88222': 714,
 'php': 5248,
 'rg21': 5837,
 '4jx': 529,
 'aiyah': 898,
 'improve': 3682,
 'already': 932,
 'gorgeous': 3241,
 'cumming': 2138,
 'thank': 6871,
 'congrats': 1985,
 '3650': 455,
 'camera': 1638,
 '09066382422': 230,
 'ave': 1168,
 '3mins': 473,
 'vary': 7331,
 'mobiles': 4603,
 'close': 1865,
 '300603': 433,
 'post': 5384,
 'bcm4284': 1264,
 'ldn': 4105,
 'princess': 5467,
 'wish': 7621,
 'command': 1934,
 'mummy': 4707,
 'father': 2819,
 'rct': 5650,
 'thnq': 6925,
 'adrian': 841,
 'rgds': 5838,
 'vatian': 7333,
 'name': 4745,
 'gautham': 3128,
 'ah': 882,
 'darlin': 2186,
 'kate': 3955,
 'doin': 2418,
 'somethin': 6362,
 'pub': 5549,
 'swan': 6708,
 'parents': 5135,
 'drink': 2474,
 'yan': 7757,
 'jiu': 3884,
 'vill': 7368,
 'frm': 3050,
 '10': 250,
 'hop': 3533,
 'parco': 5133,
 'nb': 4769,
 'cine': 1833,
 '1030': 259,
 'orc': 5031,
 'mrt': 4674,
 'hip': 3483,
 'greatest': 3278,
 'test': 6852,
 'courage': 2064,
 'earth': 2537,
 'bear': 1275,
 'defeat': 2240,
 'without': 7633,
 'losing': 4271,
 'heart': 3425,
 'gn': 3201,
 'tc': 6799,
 'arun': 1094,
 ...}

In [ ]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
np.where(X_train_np[0]!=0)

(array([  49,  631, 1001, 1009, 1619, 2259, 2977, 3023, 3344, 4188, 4554,
        4637, 4809, 4818, 5025, 5239, 5462, 5766, 5777, 6857, 7361, 7455]),)

#### **Naive Bayes Classifier**

In [ ]:
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [ ]:
y_pred = model.predict(X_test_cv)

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       965
           1       0.97      0.95      0.96       150

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115

#### **Test on a random datapoint**

In [ ]:
message = {"Want a new Video Phone?"}

In [ ]:
message_cnt = v.transform(message)

model.predict(message_cnt)

array([1])